version: '3.7'

services:
  app:
    build: .
    environment:
      DEPLOYMENT_ENVIRONMENT: 'DEV'
    env_file:
      - .env.development
    command: /bin/sh -c "cd /usr/src; ./manage.py migrate --noinput; ./manage.py runserver 0.0.0.0:8008"
    volumes:
      - .:/usr/src
    ports:
      - 8008:8008
    depends_on:
      - postgresql
    networks:
      - net

{%- if cookiecutter.use_celery == 'y' %}
  celery_worker:
    build: .
    environment:
      DEPLOYMENT_ENVIRONMENT: 'DEV'
    env_file:
      - .env.development
    command: /bin/sh -c "cd /usr/src; celery -A config.celery_app worker -l debug"
    volumes:
      - .:/usr/src
    depends_on:
      - postgresql
      - redis
    networks:
      - net
{%- endif %}

  postgresql:
    image: postgres:12
    env_file:
      - .env.development
    ports:
      - 5432:5432
    networks:
      - net

{%- if cookiecutter.use_redis == 'y' %}
  redis:
    image: redis:5.0
    networks:
      - net
{%- endif %}

networks:
  net:
